import mongoose from "mongoose";

const BlogPostSchema = new mongoose.Schema(
  {
    title: { type: String, required: true }, // Blog Post Title
    slug: { type: String, required: true, unique: true }, // Key (Primary Key)
    content: { type: String, required: true }, // Blog post content (Markdown)
    coverImageUrl: { type: String, default: null }, // Blog post cover image url
    tags: [{ type: String }], // Post tags (Array)
    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    }, // Author of blog post
    isDraft: { type: Boolean, default: false }, // Save post as draft or not
    views: { type: Number, default: 0 }, // Blog post views
    likes: { type: Number, default: 0 }, // Blog post likes
    generatedByAI: { type: Boolean, default: false }, // Blog post generated by AI or not
  },
  { timestamps: true }
);

export default mongoose.model("BlogPost", BlogPostSchema);
